### ISSUE TITLE
Notebook source

### ISSUE THREAD

**Issue by rsvp** [zjost/bayesian-linear-regression#1]
Good work! If a learner wanted to interact with the notebook, is it possible to convert from current HTML only format to ipynb? Curious why the source code itself was not commited to repo... perhaps related to rsvp/fecon235#3 math rendering problem at GitHub.

**Comment by zjost** [comment]
Thank you, I hope it was beneficial to you.  As for the code, it's in the `src` directory of this repo ([here](https://github.com/zjost/bayesian-linear-regression/blob/master/src/bayes-regression.ipynb)).  However, as you note, the link in the description of the repo is to a static page with rendered html.  If you still have problems getting to it let me know.  Cheers.
